### ISSUE TITLE
tap event

### ISSUE THREAD

**Issue by syrakozz** [kean/DFImageManager#1]
could you plz add a tap event to the image,
and if we can view them and share them it will be great

**Comment by kean** [comment]
If you want to enable share button only when the image is loaded you can [observe image property on UIImageView using KVO](http://stackoverflow.com/questions/10508422/is-there-a-way-to-get-notified-when-my-uiimageview-image-property-changes). Then you can instantiate `UIActivityViewController` with a `UIImage` object.

If you want to be able to share images before they are loaded you need to subclass `UIActivityItemProvider`. I will add `UIActivityItemProvider` subclass in future versions. It will also require a built-in support for making synchronous requests. For now on you can implement it by yourself, here's a [draft version of how it may look like](https://gist.github.com/kean/ae2b051225208ec4d871).

It's dead simple to add a tap event using `UITapGestureRecognizer`.
