### ISSUE TITLE
Is it possible to empty the cache?

### ISSUE THREAD

**Issue by thedp** [kean/DFImageManager#10]
My app loads a new image every couple of seconds, and I would like to preload into cache a couple of images in advance. I'm worried this might over use the memory.
Does DFImageManager supports a manual way to empty the cache?

You've created a very useful and powerful lib. Thank you!

**Comment by kean** [comment]
Memory cache is managed by DFImageManager (see `DFImageCache` class). It has a total cost limit that prevents memory warnings, you can [read more here](https://github.com/kean/DFImageManager/wiki/Image-Caching-Guide#image-caching-and-nscache). If memory warning happens anyway then `DFImageCache` will remove all cached images automatically.

If you still need to empty memory cache manualy see `[NSCache df_sharedImageCache]`, which is used by default image manager (be aware that it might change later).
