### ISSUE TITLE
How to load placeholder image?

### ISSUE THREAD

**Issue by mankarth004** [kean/DFImageManager#102]
Can you please help me how can I show a placeholder image (i.e; loading image for remote images) onto the DFImageView. We have this option in SDWebImage. Looking forward for the solution..

**Comment by kean** [comment]
Same as in [Nuke](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Tips%20and%20Tricks.md#display-a-placeholder) (sorry, I don't remember the exact DFImageManager APIs):

``` swift
imageView.image = UIImage(named: "placeHolder")
Nuke.loadImage(with: url, into: imageView)
```

If you worry about performance:

``` swift
Nuke.loadImage(with: url, into: imageView)
if imageView.image == nil {
    imageView.image = UIImage(named: "placeHolder")
}
```

If you need a placeholder as a method's parameter just add your own extension method.
