### ISSUE TITLE
DFImageRequestID ~> DFImageTask

### ISSUE THREAD

**Issue by kean** [kean/DFImageManager#22]
- Rename `DFImageRequestID` to `DFImageTask` (similar to [Nuke](https://github.com/kean/Nuke))
- Open some of the private `_DFImageTask` interfaces like `state`, `request`, `error`, `completionHandler` etc
- Rename `DFImageInfoRequestIDKey` to `DFImageInfoTaskKey`

**Comment by Hacoga** [comment]
I have a problem, in my app on watch.
Never put the image.. why?

CODE:

         DFImageRequest *previewRequest = [DFImageRequest requestWithResource:[NSURL URLWithString:dataObject.thumbnail]];
         DFImageRequest *fullsizeRequest = [DFImageRequest requestWithResource:[NSURL URLWithString:dataObject.thumbnail]];
        
        NSArray *requests = @[ previewRequest, fullsizeRequest ];
        DFImageFetchTask *task = [DFImageFetchTask requestImageForRequests:requests handler:^(UIImage *image, NSDictionary *info, DFImageRequest *request) {
            // Handler is called at least once
            // For more info see DFImageFetchTask class
            NSLog(@"info %@", info);
            [self.iboGroup setBackgroundImage:image];
            
        }];
        
        // Track the state of the requests
        DFImageFetchContext *context = [task contextForRequest:previewRequest];
        BOOL isPreviewFetched = context.image != nil;

**Comment by kean** [comment]
Done
