### ISSUE TITLE
df_setImageWithResource: with nil url crashes the application

### ISSUE THREAD

**Issue by Quarezz** [kean/DFImageManager#35]
DFImageManagerKit+UI.h

---

[self.imageViewIcon df_setImageWithResource:[NSURL URLWithString:data.imageUrl]];

---

Crashes here:

```
- (DFImageTask *)imageTaskForRequest:(DFImageRequest *)request completion:(DFImageRequestCompletion)completion {
    id<DFImageManaging> manager = DFManagerForRequest(request);
    if (!manager) {
        [NSException raise:NSInvalidArgumentException format:@"There are no managers that can handle the request %@", request];
    }
    return [manager imageTaskForRequest:request completion:completion];
}
```

Not really a bug, as I passed nil instead of NSURL, but still I think crashing is not the best choice.

**Comment by kean** [comment]
> Not really a bug

Yep, the resource is annotated as nonnull
`- (nullable DFImageTask *)df_setImageWithResource:(nonnull id)resource;`

> crashing is not the best choice

You are probably right, I think the UI components should be more forgiving. Thank you, I'll give it a thought.

**Comment by kean** [comment]
Done, DFImageView and UIImageView resource and request are now nullable
