### ISSUE TITLE
CocoaPods and dynamic frameworks

### ISSUE THREAD

**Issue by bonebox** [kean/DFImageManager#4]
This currently will not build if included in a dynamic framework via CocoaPods.  The issue appears to be with importing FLAnimatedImage in DFImageView.h.  It throws an error on line 27 with "'FLAnimatedImage.h' file not found."

**Comment by kean** [comment]
Thanks, I'm aware of the issue and will investigate dynamic frameworks in CocoaPods.

**Comment by kean** [comment]
I've fixed the issue with imports, please give it a try bec08eab8a936357596bfdedcead024c6abb0161

**Comment by bonebox** [comment]
Appears to be working, thanks!
