### ISSUE TITLE
Unable to compile under Xcode 7 beta 5 and iOS 9 beta 5

### ISSUE THREAD

**Issue by tomislav** [kean/DFImageManager#56]
I'm getting this error when compiling with  Xcode 7 beta 5 and iOS 9 beta 5 in `DFImageView.m`.

`Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'`

```
- (nonnull instancetype)initWithCoder:(NSCoder *)decoder {
    if (self = [super initWithCoder:decoder]) {
        [self _commonInit];
    }
    return self;
}
```

**Comment by kean** [comment]
Hi, pull request would be nice, we don't use Xcode 7 yet.

**Comment by kean** [comment]
Done (see `develop` branch). Also resolves "Method override for the designated initializer of the superclass '-init' not found" warning by marking -init unavailable where necessary.

**Comment by kean** [comment]
Also disable ATS (app transport security) in demo project.
