### ISSUE TITLE
WebP format support

### ISSUE THREAD

**Issue by diehardest** [kean/DFImageManager#57]
Hi, guys!

I'm trying to download webp image at url @"https://www.gstatic.com/webp/gallery/2.sm.webp" simply using this method

```
 - (void)setImageWithResource:(nullable id)resource targetSize:(CGSize)targetSize contentMode:(DFImageContentMode)contentMode options:(nullable DFImageRequestOptions *)options;
```

However I'm getting the error

```
Error Domain=DFImageManagerErrorDomain Code=-2 "The operation couldn’t be completed. (DFImageManagerErrorDomain error -2.)"
```

Could you help me, please?

**Comment by kean** [comment]
Hi, I've tested it in a demo project and it works fine. Did you install `DFImageManager/WebP` subspec? It's [optional](https://github.com/kean/DFImageManager#installation-with-cocoapods), you should install it explicitly.

**Comment by diehardest** [comment]
Oops, my bad, sorry. Thank you for the fast response and the great framework! Спасибо :)

**Comment by kean** [comment]
Cheers :beer: There are 2 more [optional subspecs](https://github.com/kean/DFImageManager#installation-with-cocoapods)
