### ISSUE TITLE
Background image download

### ISSUE THREAD

**Issue by yasirmturk** [kean/DFImageManager#6]
is it possible to supply a 100 images may be which the app keeps fetching and storing in the cache even when the app goes to background?

**Comment by kean** [comment]
I haven't investigated it yet, but it should be implemented using background NSURLSession. I would appreciate any ideas/code snippets/PR.

The next release (0.2.0) will be available shortly and will feature AFNetworking as a primary networking option for DFImageManager. It is already available in master. It would be a good idea to implement background downloads with a help of AFNetworking.

**Comment by kean** [comment]
This feature should **not** be included in this framework. You should use background NSURLSession directly in order to do that.
