### ISSUE TITLE
DFImageView animation

### ISSUE THREAD

**Issue by bonebox** [kean/DFImageManager#7]
I'm using a DFImageView with a default image in a UICollectionViewCell, then calling setImageWithResource: to fetch a remote image.  Is the new image transition suppose to animate?   I'm assuming that's what the allowsAnimations property is for, which says default is YES.  But the image change is very abrupt.

**Comment by kean** [comment]
There is no cross-dissolve in DFImageView. Use DFContainerImageView instead. However, I would recommend writing your own custom class for something like that.

``` swift
let container = DFImageContainerView()
container.animation = DFImageViewAnimation.CrossDissolve

container.prepareForReuse()
container.imageView.image = /* default image */
container.imageView.setImageWithResource(/* resource */)
```

There was an issue with cross-dissolve and it's fixed in version 0.2.1.

**Comment by bonebox** [comment]
Thanks. I updated to 0.2.1 and switched to DFContainerImageView instead of DFImageView.  I set the animation to DFImageViewAnimation.CrossDisolve, but they still just pop in as before.

**Comment by bonebox** [comment]
Disregard that last comment. I was using a custom podspec to pull in master before 0.2.1 was released. Not sure why it still didn't pull in the latest after updating, but changing directly to 0.2.1 fixed it.
