### ISSUE TITLE
DFImageManagerImageLoader sometimes fails to cancel fetch operations

### ISSUE THREAD

**Issue by kean** [kean/DFImageManager#71]
DFImageManagerImageLoader (private class) uses a single fetch operation for equivalent request. Executing operations are stored in a dictionary with wrapped requests as a keys. This dictionary is the only object that holds strong references to the operations.

Operations are removed from the dictionary in two places:
1. When image task is cancelled and there are no remaining tasks that are subscribed to the operation
2. When operation is complete

Operation's completion handler is called for cancelled operations. The problem arises when you start, cancel and then restart the same requests very fast. In that case there is a chance that DFImageManagerImageLoader would remove a second operation (for restarted request) when handling completion of the first operation (which was cancelled). The requests are the same, but operations are different. This would lead to the operation deallocation (actually deallocation of its wrapper) which would prevent DFImageManagerImageLoader from cancellation and reusing this operation later.

**Comment by kean** [comment]
Fixed 7491c829932ec7f42131abb2a4017dedc96b880b

**Comment by mythodeia** [comment]
@kean are you planning on releasing a new version soon? thanks

**Comment by kean** [comment]
@mythodeia yep, releasing it today. Going to drop sdwebimage? :wink:

**Comment by mythodeia** [comment]
@kean :open_mouth: oh come on! play nice!  i admit we need a major update but time is always against us. And i have to admit your work is exceptional and tempting

**Comment by kean** [comment]
any contribution would be much appreciated :)
