### ISSUE TITLE
PhotoKit crash

### ISSUE THREAD

**Issue by buithuyen** [kean/DFImageManager#76]
Hi guy,

I'm facing problem when I get images use PhotoKit. 
<img width="1885" alt="screen shot 2015-09-12 at 10 50 51 pm" src="https://cloud.githubusercontent.com/assets/5087522/9832325/2f9d8a9e-59a1-11e5-8f03-6ef8f5b21fd5.png">

Sometime, I didn't get image with real device.
![img_0451](https://cloud.githubusercontent.com/assets/5087522/9832333/793e963e-59a1-11e5-8830-e07a093c5078.PNG)

**Comment by kean** [comment]
Hi @buithuyen, too much memory is being allocated, it's obviously a video data. DFPhotosKitImageFetcher does not support assets with PHAssetMediaTypeVideo type, however demo project was trying to display them anyway. I've added a predicate to change that:

``` objective-c
PHFetchOptions *options = [PHFetchOptions new];
options.predicate = [NSPredicate predicateWithFormat:@"mediaType == %d", PHAssetMediaTypeImage];
PHFetchResult *assetsFetchResults = [PHAsset fetchAssetsInAssetCollection:moment options:options];
```

I would consider adding support for video assets in future versions, thanks for your question :)

**Comment by kean** [comment]
See #77

**Comment by buithuyen** [comment]
I hope that you will support video assets soon. Thanks for your help!

**Comment by kean** [comment]
Be aware, that you should stick with PHImageManager whenever possible. Use DFImageManager when:
a) you need to display images from Photos, network (and other sources) on the same screen
b) you need to play animated GIFs from Photos
