### ISSUE TITLE
IOS 9 Animated gif problem

### ISSUE THREAD

**Issue by korcanergun** [kean/DFImageManager#81]
Hi,

My app works fine with ios 8. But when i updated software and xcode 7, everything seems fine without animation. DFIMAGEMANAGER works as expected but GIF animations are not starting. Only first frame of GIF displaying.

```
    self.imageView = [[DFImageView alloc] initWithFrame:CGRectNull];
    self.imageView.allowsAnimations = YES;
    self.imageView.managesRequestPriorities = YES;
    [imageView prepareForReuse];
    [self.imageView setImageWithResource:[[NSBundle mainBundle] URLForResource: _icons[index] withExtension:@"gif"]];
```

Best Wishes;

**Comment by kean** [comment]
Hi,

DFImageView can no longer display animated GIF, please use DFAnimatedImageView instead (I assume that you updated to DFImageManager 1.0.0).

The reasoning behind this is that DFImageManager 1.0.0 moved from conditional compilation to be more robust. DFImageView no longer becomes FLAnimatedImageView subclass when DFImageManager/GIF subspec is installed. And DFImageManager/GIF subspec now includes new DFAnimatedImageView class that is a subclass of DFImageView. For more info see [release notes](https://github.com/kean/DFImageManager/releases/tag/1.0.0).

Cheers
