### ISSUE TITLE
Callback for progress

### ISSUE THREAD

**Issue by peterpaulis** [kean/DFImageManager#82]
After upgrading i did noticed that the progressHandler from DFImageRequestOptions is missing

whats the new alternative for a progress callback?

**Comment by kean** [comment]
Yep, it's been replaced with NSProgress a while ago.

``` objective-c
@interface DFImageTask : NSObject <NSCopying>
...
@property (nullable, atomic, readonly) NSProgress *progress;
...
```

**Comment by peterpaulis** [comment]
thats a pity, NSProgress can be monitored only using KVO, which may add some layer of problems (making sure you remove the observer and none of the objects get dealloced forehand)...

**Comment by kean** [comment]
You can use [KVOController](https://github.com/facebook/KVOController) or other similar libraries to use NSProgress with blocks.

I'm very sceptical about NSProgress but for the different reasons:
1. All its properties are readwrite
2. Ridiculous implicit progress composition
3. Performance problems, because of (2)

I'm planning to move to block-based API again in [Nuke](https://github.com/kean/Nuke).

**Comment by peterpaulis** [comment]
Just in case somebody might be interested in setting up the KVO 

<pre>
@property (nonatomic, strong) DFImageTask * imageTask;
@property (nonatomic, strong) NSProgress * monitoredProgress;
</pre>

<pre>
static void *ProgressObserverContext = &ProgressObserverContext;
- (void)dealloc {
    self.imageTask = nil;
}
////////////////////////////////////////////////////////////////////////
#pragma mark - KVO
////////////////////////////////////////////////////////////////////////
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {
    
    if (context == ProgressObserverContext) {
        
        [[NSOperationQueue mainQueue] addOperationWithBlock:^{
            
            NSProgress * progress = object;
            [self.progressLoadingView setProgress:progress.fractionCompleted animated:YES];
            
        }];
    
    } else {
        
        [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
    
    }
    
}
////////////////////////////////////////////////////////////////////////
#pragma mark - Getters / Setters
////////////////////////////////////////////////////////////////////////
- (void)setMonitoredProgress:(NSProgress *)monitoredProgress {
    
    if (_monitoredProgress) {
        [_monitoredProgress removeObserver:self forKeyPath:@"fractionCompleted" context:ProgressObserverContext];
    }
    
    _monitoredProgress = monitoredProgress;
    
    if (monitoredProgress) {
        [monitoredProgress addObserver:self forKeyPath:@"fractionCompleted" options:NSKeyValueObservingOptionNew context:ProgressObserverContext];
    }
    
}
- (void)setImageTask:(DFImageTask *)imageTask {
    
    if (_imageTask) {
        
        self.monitoredProgress = nil;
        [_imageTask cancel];
        
    }
    
    _imageTask = imageTask;
    if (imageTask) {
        
        self.monitoredProgress = imageTask.progress;
        
    }
    
}
</pre>

**Comment by peterpaulis** [comment]
btw... i found it a great pity that DFImageManager will target only iOS8+ (i had to use 0.8 for iOS7 support (which is still required by clients)) and even more, that it will be deprecated in favour of Nuke :(  so much bad news

**Comment by kean** [comment]
v0.8.0 is a solid release, you shouldn't have any problems with it.

I'm going to maintain DFImageManager for a while, but there won't be any major changes.

iOS 7 is going to die off pretty soon, and Swift is finally production-ready (for my taste) starting with Xcode 7.
<img width="250" alt="screen shot 2015-10-06 at 19 17 28" src="https://cloud.githubusercontent.com/assets/1567433/10314707/fc2b4b08-6c5e-11e5-8e96-fbbc5743faff.png">

**Comment by kean** [comment]
Nuke has a progress closure instead of NSProgress now https://github.com/kean/Nuke/issues/19

**Comment by peterpaulis** [comment]
pls, can you add this important feature also to DFImageManager... Objective-C is still mainstream and core for many existing projects

**Comment by kean** [comment]
yep, I'll think about it. I encourage you to do it yourself though. Just add atomic, readwrite `progressHandler` property  to `DFImageTask` and call it on the main thread inside `- (void)imageLoader:(nonnull DFImageManagerLoader *)imageLoader imageTask:(nonnull _DFImageTask *)task didUpdateProgressWithCompletedUnitCount:(int64_t)completedUnitCount totalUnitCount:(int64_t)totalUnitCount`. Progress handler might contain a single fractionCompleted argument.
