### ISSUE TITLE
Feature request: Download progress handler block

### ISSUE THREAD

**Issue by peterpaulis** [kean/DFImageManager#84]
Please add progress handler block for monitoring download progress... i put somewhere here a tutorial for observing NSProgress, but thats such an overload for such a task

The progress monitoring block is quite an important missing feature :(

**Comment by kean** [comment]
Hey @peterpaulis! I can no longer invest time in this project. But I'm not going to stop maintaining it any time soon - like I said in #82. If someone would create a pull request with this feature I would be glad to review and merge it.

**Comment by kean** [comment]
Closed by 6eab47a52451432167886cd0d5fdb0042d070d0f
