### ISSUE TITLE
Doesn't support iOS 8 via Carthage?

### ISSUE THREAD

**Issue by Quarezz** [kean/DFImageManager#85]
Hi, I've tried to implement DFImageManager in my project via Carthage, but as soon as I run on iOS 8 - I get crash with info:
dyld: Symbol not found: ___NSArray0__
DFImageManager.framework/DFImageManager (which was built for iOS 9.0)

I've dug a little in the project settings and found: IPHONEOS_DEPLOYMENT_TARGET = 9.0 in settings.
Does that mean that you don't support iOS 8 anymore or is this just a mistake with Carthage setup?

**Comment by kean** [comment]
My bad, deployment target is set to iOS 9.

**Comment by Quarezz** [comment]
Will you change it to different value or this is how it supposed to be?

**Comment by kean** [comment]
Yep, I'm changing it right now. It should be iOS 8.0+

**Comment by Quarezz** [comment]
Cool, thank you :+1:

**Comment by kean** [comment]
Done https://github.com/kean/DFImageManager/releases/tag/1.0.1
