### ISSUE TITLE
AFNetworking 3.x

### ISSUE THREAD

**Issue by sschizas** [kean/DFImageManager#86]
Will update s.depedancy to support AFNetworking 3.0?

**Comment by kean** [comment]
Yes, I will, probably some time this week.

**Comment by sschizas** [comment]
Any update on this one?

**Comment by kean** [comment]
Sorry, can't promise anything. I might be able to look at it today or tomorrow.

**Comment by kean** [comment]
Closed by 877ac2e5264bece8dbf9e1e6dc612c97b7b0c5ff

**Comment by sschizas** [comment]
Thx a lot
