### ISSUE TITLE
Completion handler for UICollectionViewCell

### ISSUE THREAD

**Issue by andrey-lisovskiy** [kean/DFImageManager#87]
Hi, how can I have completionHandler for UICollectionViewCell image loading?
I need to add some activityIndicator, and hide it when GIF was loaded.

**Comment by kean** [comment]
Hi, there are multiple ways to achieve that:

1) Create your own `UIImageView` / `UICollectionViewCell` subclass and use `DFImageManager` directly. That's the recommended way. There is almost no boilerplate required and you get full control over completion handler and everything. Here's an [example](https://gist.github.com/kean/e689de23ea42b942dddb), you can also check `DFImageView` and `UIImageView+DFImageManager` implementation.
2) Add KVO on `state` property of `DFImageTask`
3) Extend a `completionHandler` of `DFImageTask`

``` objective-c
[imageView df_prepareForReuse];

DFImageTask *task = [imageView df_setImageWithRequest:nil];

NSLog(@"show activity indicator");

DFImageTaskCompletion handler = task.completionHandler;
task.completionHandler = ^(UIImage * _Nullable image, NSError * _Nullable error, DFImageResponse * _Nullable response, DFImageTask * _Nonnull task) {
    if (handler) {
        handler(image, error, response, task);
    }
    NSLog(@"hide activity indicator");
};
```

4) Override `-didCompleteImageTask:withImage:` method if you are using `DFImageView`

**Comment by andrey-lisovskiy** [comment]
thanks
