### ISSUE TITLE
Check is image in cache

### ISSUE THREAD

**Issue by diehardest** [kean/DFImageManager#89]
Is it possible to check is image in cache (on-disk or memory) without running a DFImageTask?

**Comment by kean** [comment]
Yes and no. There are two cache levels: memory cache and disk cache. See [Image Caching Guide](https://github.com/kean/DFImageManager/wiki/Image-Caching-Guide) for more info.

**Memory cache:**

No. This feature is available in [Nuke](https://github.com/kean/Nuke). It's much more open than DFImageManager.

**Disk cache:**

Yes, but it's not very straightforward. Create custom DFImageMananger (see DFImageManager+SharedManager.m) with custom NSURLCache and use NSURLCache directly.

**Comment by kean** [comment]
The reasons behind lack of first-class support for this feature: "cache" is a transient thing, possible method that checks if the image is cached might return YES, but the image would not be available seconds later. More info [here](https://github.com/kean/DFImageManager/pull/42).

I would recommend to design your app in a way that doesn't rely on whether image exists in cache or not. 

It's also possible to run DFImageTask with disabled network access (only cache would be queried). It might be just what you are looking for:

``` objective-c
DFMutableImageRequestOptions *options = [DFMutableImageRequestOptions new];
options.allowsNetworkAccess = NO;

DFImageRequest *request = [DFImageRequest requestWithResource:<#resource#> targetSize:<#target_size#> contentMode:<#content_mode#> options:options.options];

DFImageTask *task = [DFImageManager imageTaskForRequest:request completion:<#completion#>];
```

NSURLRequests for such tasks would be created with NSURLRequestReturnCacheDataDontLoad cachePolicy.

As an alternative to `allowsNetworkAccess` property you can set cachePolicy directly (see DFURLRequestCachePolicyKey and DFAFRequestCachePolicyKey keys which are fetcher-specific).

**Comment by diehardest** [comment]
Thank you for the response! The reason why I need to check app cache - I want to show tiny preview if image not loaded yet. Of course, if target image already on device I don't need to download and animate preview, so that's why I looked for cache check. DFImageTask with disabled network access works fine, and solves the issue, thank you again for the hint and the awesome library!

**Comment by kean** [comment]
Thanks, glad that it worked! 

In our own apps we tend to just start two DFImageTasks at the same time (preview+fullsize). Then cancel preview task if fullsize task completes first. We prefer this strategy to progressive JPEG because fullsize images are used only in photo gallery, while previews are used on multiple other screens. Hope that it made sense :)
