### ISSUE TITLE
DFImageView and Aspect Fit

### ISSUE THREAD

**Issue by bonebox** [kean/DFImageManager#9]
Aspect fit doesn't appear to be working properly when setting a DFImageView's image using setImageWithRequest: and the request's contentMode set to DFImageContentModeAspectFit.  Mine are doing a fill instead.

**Comment by kean** [comment]
DFImageContentMode controls resizing of the loaded image. Did you set the contentMode of the UIImageView (`UIViewContentMode contentMode`?

**Comment by bonebox** [comment]
Hmm, contentMode was set to Aspect Fit in Interface Builder (and works with normal UIImageView), but doesn't work after changing the class to DFImageView.  However, setting it programatically fixed it.

**Comment by kean** [comment]
Right, DFImageView overwrites contentMode after `[super initWithCoder:decoder]` is called, which it is not supposed to do. I will streamline the DFImageView interface in the next version, it's very cluttered.

**Comment by kean** [comment]
Btw, I would really appreciate pull requests that fix UI components. I can't focus on them at the moment.

**Comment by mythodeia** [comment]
@kean i am planning on replacing my old caching engine with your shiny one and remembered of this issue. has this been resolved? 
thanks for your time and for open sourcing this great piece of code

**Comment by kean** [comment]
@mythodeia I wasn't able to work on this for awhile, so no it hasn't. UI components isn't my first priority, we use custom classes in our projects at work. If you feel like changing something it would be nice to have in a pull request.

I will put some time in this project in a nearest future, maybe this week. I'm planning to bring nullability support and maybe some other features.

**Comment by mythodeia** [comment]
:+1: thanks a lot for your time and this magnificent library

**Comment by kean** [comment]
Fixed
