### ISSUE TITLE
Custom keyboard extension crashes

### ISSUE THREAD

**Issue by andrey-lisovskiy** [kean/DFImageManager#92]
I have custom keyboard extension with collectionView of gifs from server.
The problem is that when I'm scrolling - keyboard crashes if memory allocation more than 40 Mb.

**Comment by kean** [comment]
I believe this is solved? https://github.com/kean/DFImageManager/issues/88
FLAnimatedImage introduced some memory-usage improvements recently, this might be helpful https://github.com/Flipboard/FLAnimatedImage/pull/117

**Comment by andrey-lisovskiy** [comment]
Why I cannot see [these](https://github.com/Flipboard/FLAnimatedImage/commit/0b4886003f34d1b89cd1b5ec9552852c08891c15) changes when installing FLAnimatedImage with
pod 'DFImageManager/GIF'
?

**Comment by kean** [comment]
They haven't been released yet. Latest FLAnimatedImage version 1.0.10, and it was released more then a month ago.

**Comment by andrey-lisovskiy** [comment]
Ok, thanks.

**Comment by kean** [comment]
You could try to use FLAnimatedImage from master:

``` ruby
pod "FLAnimatedImage", :git => "https://github.com/Flipboard/FLAnimatedImage", :branch => "master"
```

**Comment by andrey-lisovskiy** [comment]
Big thanks!
