### ISSUE TITLE
Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'

### ISSUE THREAD

**Issue by CAMOBAP** [kean/DFImageManager#94]
DFImageManager/DFImageManager/Source/UI/DFImageView.m:58:12: Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'

**Comment by kean** [comment]
Hi, I don't see this problem in master. I'm using Xcode 7.2.

**Comment by CAMOBAP** [comment]
Sorry for spam, I have found the same issue #56 which closed

**Comment by CAMOBAP** [comment]
When locally I change:

```
- (nonnull instancetype)initWithCoder:(NSCoder *)decoder {
    if (self = [super initWithCoder:decoder]) {
        [self _commonInit];
    }
    return self;
}
```

to

```
- (instancetype)initWithCoder:(NSCoder *)decoder {
    if (self = [super initWithCoder:decoder]) {
        [self _commonInit];
    }
    return self;
}
```

It works without error

**Comment by kean** [comment]
That's ok. Yeah, I should probably remove nullability annotations from .m files. Xcode used to add them automatically but it no longer does that.

**Comment by CAMOBAP** [comment]
I will prepare pull request

**Comment by CAMOBAP** [comment]
@kean  Could you please review?

**Comment by lei-zxx** [comment]
nice

**Comment by BboyKai1992** [comment]
666
