### ISSUE TITLE
Original downloaded image

### ISSUE THREAD

**Issue by andrey-lisovskiy** [kean/DFImageManager#99]
How can I get original download image from DFAnimatedImageView? When I'm trying to get from **dfImageView.image** it returns image scaled to it's frame in view.

**Comment by HTKT** [comment]
The same question. Looking forward owner's answer.

**Comment by kean** [comment]
Sorry, missed your question @andrey-lisovskiy.

``` objective-c
@interface DFAnimatedImageView : DFImageView

/*! Inner animated image view used for GIF playback.
 */
@property (nonnull, nonatomic, readonly) FLAnimatedImageView *animatedImageView;
```

Isn't that what you need? You get access to the original image data and all that.
